const actionTypes = Object.freeze({
    // Location
    READ_PROVINCES_START: 'READ_PROVINCES_START',
    READ_PROVINCES_SUCCESS: 'READ_PROVINCES_SUCCESS',
    READ_PROVINCES_FAIL: 'READ_PROVINCES_FAIL',

    READ_DISTRICTS_START: 'READ_DISTRICTS_START',
    READ_DISTRICTS_SUCCESS: 'READ_DISTRICTS_SUCCESS',
    READ_DISTRICTS_FAIL: 'READ_DISTRICTS_FAIL',

    READ_WARDS_START: 'READ_WARDS_START',
    READ_WARDS_SUCCESS: 'READ_WARDS_SUCCESS',
    READ_WARDS_FAIL: 'READ_WARDS_FAIL',

    // User
    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    USER_LOGOUT_START: 'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',

    USER_UPDATE_START: 'USER_UPDATE_START',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',

    READ_USER_PROFILE_PAGE_START: 'READ_USER_PROFILE_PAGE_START',
    READ_USER_PROFILE_PAGE_SUCCESS: 'READ_USER_PROFILE_PAGE_SUCCESS',
    READ_USER_PROFILE_PAGE_FAIL: 'READ_USER_PROFILE_PAGE_FAIL',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    READ_LIST_USERS_START: 'READ_LIST_USERS_START',
    READ_LIST_USERS_SUCCESS: 'READ_LIST_USERS_SUCCESS',
    READ_LIST_USERS_FAIL: 'READ_LIST_USERS_FAIL',

    // Post
    CREATE_POST_START: 'CREATE_POST_START',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAIL: 'CREATE_POST_FAIL',

    READ_POST_START: 'READ_POST_START',
    READ_POST_SUCCESS: 'READ_POST_SUCCESS',
    READ_POST_FAIL: 'READ_POST_FAIL',

    READ_POST_OF_USER_START: 'READ_POST_OF_USER_START',
    READ_POST_OF_USER_SUCCESS: 'READ_POST_OF_USER_SUCCESS',
    READ_POST_OF_USER_FAIL: 'READ_POST_OF_USER_FAIL',

    DELETE_POST_START: 'DELETE_POST_START',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL: 'DELETE_POST_FAIL',
});

export default actionTypes;
