const actionTypes = Object.freeze({
    // Location
    READ_PROVINCES_START: 'READ_PROVINCES_START',
    READ_PROVINCES_SUCCESS: 'READ_PROVINCES_SUCCESS',
    READ_PROVINCES_FAIL: 'READ_PROVINCES_FAIL',

    READ_DISTRICTS_START: 'READ_DISTRICTS_START',
    READ_DISTRICTS_SUCCESS: 'READ_DISTRICTS_SUCCESS',
    READ_DISTRICTS_FAIL: 'READ_DISTRICTS_FAIL',

    READ_WARDS_START: 'READ_WARDS_START',
    READ_WARDS_SUCCESS: 'READ_WARDS_SUCCESS',
    READ_WARDS_FAIL: 'READ_WARDS_FAIL',
});

export default actionTypes;
